---
language: python
os: linux
dist: jammy

virtualenv:
  system_site_packages: false

jobs:
  include:
    - dist: bionic
      python: 3.7
      env:
        - PIP_VERSION=19.0
    - dist: focal
      python: 3.8
      env:
        - PIP_VERSION=20.0.2
    - python: 3.8
      env:
        - PIP_VERSION=22.1
    - python: 3.9
      env:
        - PIP_VERSION=20.0.2
    - python: 3.9
      env:
        - PIP_VERSION=22.1
# seems nose has trouble with py3.10
#    - python: 3.10
#      env:
#        - PIP_VERSION=22.1
    - python: 3.9
      env:
        - FLAKE8=1

before_install:
  # setup git
  # TODO: change to main
  - git config --global init.defaultBranch master
  - git config --global advice.detachedHead false
  - git config --global pull.rebase false
  # For tests running hg command
  # set up username
  - echo '[ui]' > ~/.hgrc
  - echo 'username = oca-test' >> ~/.hgrc
  # if the wheel package is present, then pip will build an unusable wheel
  # for zc.recipe.egg (see commit msg for analysis of that)
  - pip uninstall -y wheel
  - echo -e "[easy_install]\nzip_ok = False" > ~/.distutils.cfg
  - '[ -n "$PIP_VERSION" ] && pip install pip==$PIP_VERSION || true'

install:
  # zc.buildout < 3.0.0 depends on easy_install, dropped by setuptools 52.0
  - pip install "setuptools<52.0"
  - pip install -e .[test]
  - pip install coverage
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov

script:
  - |
    if [[ "$FLAKE8" = "1" ]];
    then
        pip install flake8;
        flake8 oca;
    fi
  - python setup.py nosetests
  - ./codecov
  # install sphinx only after running tests to avoid failing tests
  # gracinet: after merging of the PR this commit concludes,
  # installing sphinx should have no impact on the tests
  - pip install sphinx sphinx_bootstrap_theme; python setup.py build_sphinx

after_script:
  # Dump version of all installed packages
  - |
    echo 'Versions of all installed packages';
    echo '==================================';
    pip freeze -l oca.recipe.odoo

after_success:
  - coveralls
