---
language: python
os: linux
dist: bionic

virtualenv:
  system_site_packages: false

jobs:
  include:
    - python: "3.7"
      env:
        - COVERALLS='>=3.3.1'
    - python: "3.8"
      env:
        - COVERALLS='>=3.3.1'
    - python: "3.9"
      env:
        - COVERALLS='>=3.3.1'
        - FLAKE8=1

before_install:
  # setup git
  # TODO: change to main
  - git config --global init.defaultBranch master
  - git config --global advice.detachedHead false
  # For tests running hg command
  # set up username
  - echo '[ui]' > ~/.hgrc
  - echo 'username = anybox-test' >> ~/.hgrc
  # if the wheel package is present, then pip will build an unusable wheel
  # for zc.recipe.egg (see commit msg for analysis of that)
  - pip uninstall -y wheel

install:
  # zc.buildout < 3.0.0 depends on easy_install, dropped by setuptools 52.0
  - pip install "setuptools<52.0"
  - pip install coveralls${COVERALLS}
  - pip install -e .[test]

script:
  - |
    if [[ "$FLAKE8" = "1" ]];
    then
        pip install flake8;
        flake8 anybox;
    fi
  - python setup.py nosetests
  # install sphinx only after running tests to avoid failing tests
  # gracinet: after merging of the PR this commit concludes,
  # installing sphinx should have no impact on the tests
  - pip install sphinx sphinx_bootstrap_theme; python setup.py build_sphinx

after_script:
  # Dump version of all installed packages
  - |
    echo 'Versions of all installed packages';
    echo '==================================';
    pip freeze -l anybox.recipe.odoo

after_success:
  - coveralls
