name: Build and commit documentation

on:
  push:
    branches: ["main"]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Check out oca.recipe.odoo
        uses: actions/checkout@v2
        with:
          path: oca.recipe.odoo
      - name: Check out oca.recipe.odoo
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Requirements Installation
        run: |
          pip install sphinx sphinx_bootstrap_theme zc.recipe.egg
          pip install ./oca.recipe.odoo
      - name: Build Docs
        run: |
          cd oca.recipe.odoo
          mkdir -p doc/source/.static
          python3 -m sphinx -W -q doc ../gh-pages
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "."
          branch: "gh-pages"
          cwd: "gh-pages"
          default_author: github_actions
          message: "[UPD] HTML documentation"
